---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/deploy:2025.01.1
      - image: cimg/postgres:17.3
        environment:
          PGHOST: localhost
          POSTGRES_USER: tournaments_test
          POSTGRES_PASSWORD: tournaments_test
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image
          command: docker image build --target=prod --tag=tournaments-mgmt-backend:${CIRCLE_SHA1} .
      - run:
          name: Run Odoo tests
          command: |
            docker container run \
              --rm --tty \
              --env DB_HOST=localhost \
              --env DB_PORT=5432 \
              --env DB_USERNAME=tournaments_test \
              --env DB_PASSWORD=tournaments_test \
              --env DB_NAME=tournaments_test \
              --env MODE=odoo-test \
              tournaments-mgmt-backend:${CIRCLE_SHA1}
      - run:
          name: Run API tests
          command: |
            docker container run \
              --rm --tty \
              --env DB_HOST=localhost \
              --env DB_PORT=5432 \
              --env DB_USERNAME=tournaments_test \
              --env DB_PASSWORD=tournaments_test \
              --env DB_NAME=tournaments_test \
              --env MODE=api-test \
              tournaments-mgmt-backend:${CIRCLE_SHA1}
workflows:
  main:
    jobs:
      - build
