---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/deploy:2025.01.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image
          command: docker image build --target=prod --tag=tournaments-mgmt-backend:${CIRCLE_SHA1} .
      - run:
          name: Create Docker network
          command: docker network create testnet
      - run:
          name: Run PostgreSQL test server
          command: |
            mkdir -p /docker-entrypoint-initdb.d
            echo \<<EOF > /docker-entrypoint-initdb.d/init.sql
            CREATE USER tournaments_test CREATEDB ENCRYPTED PASSWORD 'tournaments_test';
            EOF
            docker container run \
              --detach \
              --network testnet \
              --name postgres \
              --env POSTGRES_USER=postgres \
              --env POSTGRES_PASSWORD=postgres \
              --env POSTGRES_DB=postgres \
              --tmpfs /var/lib/postgresql/data \
              --volume /docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d \
              cimg/postgres:17.3
      - run:
          name: Run Odoo tests
          command: |
            docker container run \
              --rm --tty \
              --network testnet \
              --env DB_HOST=postgres \
              --env DB_PORT=5432 \
              --env DB_USERNAME=tournaments_test \
              --env DB_PASSWORD=tournaments_test \
              --env DB_NAME=tournaments_test \
              --env MODE=odoo-test \
              tournaments-mgmt-backend:${CIRCLE_SHA1}
      - run:
          name: Run API tests
          command: |
            docker container run \
              --rm --tty \
              --network testnet \
              --env DB_HOST=postgres \
              --env DB_PORT=5432 \
              --env DB_USERNAME=tournaments_test \
              --env DB_PASSWORD=tournaments_test \
              --env DB_NAME=tournaments_test \
              --env MODE=api-test \
              tournaments-mgmt-backend:${CIRCLE_SHA1}
      - run:
          name: Close PostgreSQL test server
          command: |
            docker container stop postgres
            docker container rm postgres
workflows:
  main:
    jobs:
      - build
