POST http://localhost:8000/api/public/v1/backoffice/users/login
Content-Type: application/json

{
  "login": "tournaments",
  "password": "tournaments"
}

###
GET http://localhost:8000/api/public/v1/backoffice/users/validate
Authorization: Token tUI-ufrR-n9o16JkSLeUWQ==kQfO7snlypZrlbGhjf_6Bg==YFPfhUGo4bdkN5Isra9m-MiDTQqRyoMwp-p4JinD1IkojYEzt8O3coCs3DPAjzY_Zbn2cQk3BwHEwgTdYbcZDIgUgNb5eGx7FXhJfw8b6RGLSj-DiQVmalfWLsbmSkY9wIHPG2Umxm3-7fa06l8ODv_YVV1ouaTpvKpuNtcsBWreC3IytR38ji6wpyySYQ==
