{
    "name": "PEGI Ratings",
    "version": "18.0.1.0.0",
    "category": "Tournaments",
    "summary": "PEGI Ratings for video games",
    "sequence": 0,
    "author": "",
    "license": "GPL-3",
    "depends": [],
    "data": [
        "data/pegi_age.xml",
        "data/pegi_content.xml",
        "security/models/age.xml",
        "security/models/content.xml",
        "views/age.xml",
        "views/content.xml",
        "actions/age.xml",
        "actions/content.xml",
    ],
    "application": False,
}
