{
    "name": "Tournament Showcases",
    "version": "18.0.0.3.0",
    "category": "Tournaments",
    "summary": "Showcases management for tournaments",
    "sequence": 0,
    "author": "",
    "license": "GPL-3",
    "depends": [
        "tournaments",
    ],
    "data": [
        "data/ir_module_category.xml",
        "data/tournaments_pane_type.xml",
        "security/profiles.xml",
        "security/access/pane.xml",
        "security/access/pane_type.xml",
        "security/access/showcase.xml",
        "security/access/showcase_pane.xml",
        "actions/pane.xml",
        "actions/pane_type.xml",
        "actions/showcase.xml",
        "menu/items.xml",
        "views/pane.xml",
        "views/pane_type.xml",
        "views/showcase.xml",
        "views/showcase_pane.xml",
    ],
    "application": True,
}
